export enum ExerciseType {
  CARDIO_TIME= 'CARDIO_TIME',
  CARDIO_DISTANCE= 'CARDIO_DISTANCE',
  BODY_WEIGHT_REPEATS = 'BODY_WEIGHT_REPEATS',
  BODY_WEIGHT_TIME = 'BODY_WEIGHT_TIME',
  FREE_WEIGHT = 'FREE_WEIGHT'
}
