export enum ExerciseGroups {
  CHEST = 'CHEST',
  SHOULDERS = 'SHOULDERS',
  UPPER_BACK = 'UPPER_BACK',
  LOWER_BACK = 'LOWER_BACK',
  LEGS = 'LEGS',
  BICEPS = 'BICEPS',
  TRICEPS = 'TRICEPS',
  CUSTOM = 'CUSTOM'
}
