export enum ExerciseType {
  CARDIO_TIME= 'CARDIO_TIME',
  CARDIO_DISTANCE= 'CARDIO_DISTANCE',
  BODY_WEIGHT_REPEATS = 'BODY_WEIGHT_REPEATS',
  BODY_WEIGHT_TIME = 'BODY_WEIGHT_TIME',
  WEIGHT_TRAINING = 'WEIGHT_TRAINING'
}
