export enum Muscles {
  PECTORALIS_MAJOR = 'PECTORALIS_MAJOR',
  PECTORALIS_MINOR = 'PECTORALIS_MINOR',
  TRICEPS = 'TRICEPS',
  BICEPS = 'BICEPS',
  DELTOID = 'DELTOID',
  TERES_MAJOR = 'TERES_MAJOR',
  LATISSIMUS_DORSI = 'LATISSIMUS_DORSI',
  SERRATUS_ANTERIOR = 'SERRATUS_ANTERIOR'
}
